### ISSUE TITLE
Is there any experience on determining the value of margin ?

### ISSUE THREAD

**Issue by woshilaixuexide** [hizhangp/triplet#10]
Hello,
Do you have any idea on how to determine the value of the margin in triplet loss formula? I saw you assigned 0.2 to the margin in your code. But I also noticed other people assigned 1 to it somewhere else. Can you give me some tips on choosing the value of margin ? Thank you a lot !

**Comment by hizhangp** [comment]
I assign 0.2 to the margin based on the [paper](https://arxiv.org/abs/1503.03832v1).
