### ISSUE TITLE
训练时，跑tripletsample层反向出错

### ISSUE THREAD

**Issue by gaojie0105** [hizhangp/triplet#11]
tripletsample_layer.py", line 102, in backward
    bottom[0].diff[...] = bottom_diff
ValueError: could not broadcast input array from shape (200,128) into shape (50,128)
我batchsize设的50

**Comment by hizhangp** [comment]
改前一个bug时[这一行](https://github.com/hizhangp/triplet/blob/master/triplet/tripletsample_layer.py#L95)没有相应修改，现在已经修正了。
