### ISSUE TITLE
Why i got this error ? Thanks

### ISSUE THREAD

**Issue by iamZe** [hizhangp/triplet#12]
Traceback (most recent call last):
  File "casiaWebface/triplet-master/train.py", line 94, in <module>
    sw = SolverWrapper(solver, output_dir, pretrained_model, gpu_id, data)
  File "casiaWebface/triplet-master/train.py", line 32, in __init__
    self.solver.net.layers[0].set_data(data)
  File "/home/zlu/caffe/casiaWebface/triplet-master/triplet/data_layer.py", line 77, in set_data
    self._shuffle_data()
  File "/home/zlu/caffe/casiaWebface/triplet-master/triplet/data_layer.py", line 22, in _shuffle_data
    np.random.choice(self._data._sample_person[person]))
  File "mtrand.pyx", line 1110, in mtrand.RandomState.choice (numpy/random/mtrand/mtrand.c:17158)
ValueError: a must be non-empty

**Comment by hizhangp** [comment]
It seems that your `data` is empty.

**Comment by iamZe** [comment]
@hizhangp 
I0703 01:18:34.885184 26537 solver.cpp:218] Iteration 0 (0 iter/s, 1.36157s/100 iters), loss = 0.18992
I0703 01:18:34.885309 26537 sgd_solver.cpp:105] Iteration 0, lr = 0.1
I0703 01:20:44.729997 26537 solver.cpp:218] Iteration 100 (0.770155 iter/s, 129.844s/100 iters), loss = 0.201603
I0703 01:20:44.730120 26537 sgd_solver.cpp:105] Iteration 100, lr = 0.1
I0703 01:22:54.650033 26537 solver.cpp:218] Iteration 200 (0.769711 iter/s, 129.919s/100 iters), loss = 0.22004
I0703 01:22:54.650209 26537 sgd_solver.cpp:105] Iteration 200, lr = 0.1
I0703 01:25:04.546234 26537 solver.cpp:218] Iteration 300 (0.769853 iter/s, 129.895s/100 iters), loss = 0.195984
I0703 01:25:04.546385 26537 sgd_solver.cpp:105] Iteration 300, lr = 0.1
I0703 01:27:14.541882 26537 solver.cpp:218] Iteration 400 (0.769264 iter/s, 129.994s/100 iters), loss = 0.199572
I0703 01:27:14.542065 26537 sgd_solver.cpp:105] Iteration 400, lr = 0.1
I0703 01:29:24.441956 26537 solver.cpp:218] Iteration 500 (0.76983 iter/s, 129.899s/100 iters), loss = 0.219658
I0703 01:29:24.442131 26537 sgd_solver.cpp:105] Iteration 500, lr = 0.1
I0703 01:31:34.396708 26537 solver.cpp:218] Iteration 600 (0.769506 iter/s, 129.954s/100 iters), loss = 0.175274
I0703 01:31:34.396873 26537 sgd_solver.cpp:105] Iteration 600, lr = 0.1
I0703 01:33:44.343561 26537 solver.cpp:218] Iteration 700 (0.769553 iter/s, 129.946s/100 iters), loss = 0.170062
I0703 01:33:44.343732 26537 sgd_solver.cpp:105] Iteration 700, lr = 0.1
I0703 01:35:54.284373 26537 solver.cpp:218] Iteration 800 (0.769588 iter/s, 129.94s/100 iters), loss = 0.217221
I0703 01:35:54.284571 26537 sgd_solver.cpp:105] Iteration 800, lr = 0.1
I0703 01:38:04.217398 26537 solver.cpp:218] Iteration 900 (0.769635 iter/s, 129.932s/100 iters), loss = 0.213611

我的triplet loss一直在振荡，尝试过调节margin和hard-neg ratio，还是这个现象，请问对这个有什么建议吗？谢谢

**Comment by hizhangp** [comment]
减小学习率试试。

**Comment by iamZe** [comment]
我的训练数据有40多万张，但是sampledata成功读对了subject的数目，但是图像总数不对，不知道为什么

**Comment by iamZe** [comment]
@hizhangp 
![image](https://user-images.githubusercontent.com/11495373/27785036-d97451d6-600e-11e7-9247-fc88709fc5af.png)
![image](https://user-images.githubusercontent.com/11495373/27785041-e0f7d798-600e-11e7-8d82-6e390f436683.png)
这是我的训练数据的path，data我检查过了是对的，但是还是出第一个的那种错误，ValueError: a must be non-empty，方便帮我看一下吗？

**Comment by hizhangp** [comment]
可能是你的图片存放方式和代码的读取方式不兼容，你可以用IDE找到不一样的地方。

**Comment by iamZe** [comment]
@hizhangp 另外一个问题就是ValueError: a must be non-empty，print出来data是正确的，但是shuffle时就会出错，会是data layer的问题吗

**Comment by iamZe** [comment]
@hizhangp 改变training-ratio为1的话，shuffle时ValueError: a must be non-empty就会消失，但是test时出现了'DataLayer' object has no attribute '_data'的错误

**Comment by hizhangp** [comment]
是因为在solver中没有注释test的原因，已修改。
