### ISSUE TITLE
AttributeError: 'DataLayer' object has no attribute '_data'

### ISSUE THREAD

**Issue by Johere** [hizhangp/triplet#13]
您好！train.py中训练之前确实执行了self.solver.net.layers[0].set_data(data)，但是还是会报这个错误。打印的中间信息似乎说明这里实例化了两个网络，一个phase是0，一个phase是1，请问我错在哪了呢？网络结构用的是您贴出来的vgg16-face...谢谢！
![image](https://user-images.githubusercontent.com/8957410/27863180-7efbd356-61bb-11e7-9168-2f603a6019f3.png)

**Comment by hizhangp** [comment]
是因为在solver中没有注释test的原因，已修改。

**Comment by Johere** [comment]
@hizhangp 可以运行了，真的非常感谢！
