### ISSUE TITLE
vgg16_face.prototxt每一层的学习率因子都是0吗？

### ISSUE THREAD

**Issue by Johere** [hizhangp/triplet#14]
@hizhangp 您好  请教一个问题，您的网络结构vgg16_face.prototxt，为什么每一层的学习率因子都是0呢？最后一层fc9_1是1，bias的学习率因子也是0。这样可以学到东西吗？
![image](https://user-images.githubusercontent.com/8957410/27897178-25a2bbbc-6251-11e7-9047-69ddd6e848db.png)
![image](https://user-images.githubusercontent.com/8957410/27897184-31f0e4c0-6251-11e7-942a-838f8226144b.png)

**Comment by hizhangp** [comment]
这是frozen前半部分网络层，然后finetune后半部分的方法。

**Comment by Johere** [comment]
噢噢那就是说pre-trained的模型是先用softmax训练得到的是吗？

**Comment by hizhangp** [comment]
是的，如果数据足够的话你也可以尝试直接从空白开始训练，而不用frozen。

**Comment by Johere** [comment]
那数据足够是什么概念呢   我下载的casia_webface数据集包含10575个人，494414张照片，这样可以从空白开始训练吗？

**Comment by hizhangp** [comment]
可以。

**Comment by Johere** [comment]
好的，非常感谢！
