### ISSUE TITLE
ValueError: could not broadcast input array from shape (270,128) into shape (55,128)？

### ISSUE THREAD

**Issue by DaleAG** [hizhangp/triplet#4]
Hi, hizhangp, I have some problems during I running it, hoping you can give some advice, Thank you!

1.In  tripletsample_layer.py，in the loop  `for j in range(len(label_index_map[anchor_label])):`

> top_anchor.append(anchor)
> top_positive.append(positive)
> top_negative.append(negative)
> self.index_map.append([i, positive_index, negative_index])

There is following error

> Solving...
> I0829 15:46:58.676357 13370 solver.cpp:341] Iteration 0, Testing net (#0)
> Semi-hard failed
> Semi-hard failed
> Traceback (most recent call last):
>   File "python/train.py", line 98, in <module>
>     sw.train_model(max_iters)
>   File "python/train.py", line 60, in train_model
>     self.solver.step(1)
>   File "/home/zeng/caffe-master_p1/python/triplet/tripletsample_layer.py", line 102, in backward
>     bottom[0].diff[...] = bottom_diff
> ValueError: could not broadcast input array from shape (270,128) into shape (55,128)

So I put it into `for i in xrange(bottom[0].num):`  Is it correct?

2.test_iter can only to be 0,why？

Need your answer,thank you!

**Comment by hizhangp** [comment]
@DaleGuo1995 In `tripletsample_layer.py`, there are some indents added by mistake, I've fixed the bug.

**Comment by hizhangp** [comment]
@DaleGuo1995 Test is just not implemented in the model, you can modify `train.prototxt` to add test layer.
