### ISSUE TITLE
data_layer.py "while len(sample_person) > 0:" ?

### ISSUE THREAD

**Issue by youhangtian** [hizhangp/triplet#5]
Hi, hizhangp,
In this while loop, len(sample_person) does not decrease, right? How would it become 0?

**Comment by hizhangp** [comment]
@youhangtian Yes, the keys in sample_person need to be deleted when its length == 0, I've added the missing expressions.

**Comment by louielu1027** [comment]
@hizhangp 这个工程里面如果训练样本里有人只有一张图片的话，是不是跑不了？

**Comment by louielu1027** [comment]
你程序里好像是分割了训练样本，分成训练和测试
