### ISSUE TITLE
The loss remains high after thousands of iterations

### ISSUE THREAD

**Issue by woshilaixuexide** [hizhangp/triplet#8]
您好！我使用您的代码在Facescrub上训练。我在pretrain（对530个人进行分类）中，iteration经过3000多之后loss仍然一直保持6.25左右徘徊。accuracy也是不到0.01%，所以想问问。由于我在车辆识别上也在做类似FaceNet的任务，我仿照您的代码也写了车辆型号的分类，loss也是一样的趋势，保持5以上。我想请问这个趋势正常吗？周围同事说这个趋势不常见，所以想问问您！谢谢！

**Comment by hizhangp** [comment]
这个学习过程应该是不正常的，只是使用pretrain的网络训练，最终的准确率也是可以达到90%以上的，你需要检查一下代码在更改过程中出现了bug，以及你可以适当的调整学习率的大小试试。
