### ISSUE TITLE
tripletsample_layer中的困惑

### ISSUE THREAD

**Issue by piaozhx** [hizhangp/triplet#9]
您好！您在[tripletsample_layer.py](https://github.com/hizhangp/triplet/blob/master/triplet/tripletsample_layer.py#L73)中，第73行至75行是不是少了一个缩进？否则上面关于semi-hard的计算部分就没有意义了，每次都取最后一个？

**Comment by hizhangp** [comment]
谢谢提醒，少了一个缩进已经更改
